@param String title

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <!--suppress HtmlUnknownTarget -->
    <link rel="stylesheet" href="/css/styles.css" type="text/css">
</head>
<body>
    <h1>${title}</h1>
    <p>Welcome to my Spring application with JTE!</p>
</body>
</html>
